### ISSUE TITLE
How to set want_check_browser in GUI?

### ISSUE THREAD

**Issue by mhdakhtar8** [breuerfelix/instapy-gui#101]
Hi,

Since "Isitdownoritsjustme" is also down, GUI cant get to Instagram. How do we go around this?

or how to set want_check_browser parameter in GUI?

**Comment by breuerfelix** [comment]
this is interesting .... is this a parameter in the instapy constructor right ?

**Comment by mhdakhtar8** [comment]
This is set under Sesstion tag

`session = InstaPy(username=insta_username, password=insta_password, want_check_browser=False)`

**Comment by breuerfelix** [comment]
should be added when the pipeline uploaded the new version :) thanks for mentioning this !
