### ISSUE TITLE
Error 522 

### ISSUE THREAD

**Issue by s2339956** [breuerfelix/instapy-gui#102]
CRITICAL [2020-05-19 18:12:27] [s2338856]  Unable to login to Instagram! You will find more information in the logs above.
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

INFO [2020-05-19 18:12:29] [s2338856]  Sessional Live Report:
	|> No any statistics to show

[Session lasted 57.93 seconds]
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-05-19 18:12:31] [s2338856]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

**Comment by breuerfelix** [comment]
this seems to be an error with instapy and not with instapy gui :)
