### ISSUE TITLE
Follow private accounts

### ISSUE THREAD

**Issue by riadhrebei** [breuerfelix/instapy-gui#103]
Hello @breuerfelix 
InstaPy GUI has helped me alot for building Instagram profils, but I can't figure out how to deactivate skipping private accounts. As in my country lots of users prefer to stay private than have public profils. I know it's a command *session.set_skip_users(skip_private=False* , as I read in the @timgrossmann documentation but I can't seem to find it on the GUI, is there any files I need to edit on my Mac ?
I appreciate the help in advance. Thank you!

**Comment by breuerfelix** [comment]
hey ! glad that you like instapy gui :)

https://i.imgur.com/doQEmIK.png

since i didnt implement the search function its sometimes hard to find the correct function but here it is :)
