### ISSUE TITLE
SSL error on start.py

### ISSUE THREAD

**Issue by LorenzoBottaccioli** [breuerfelix/instapy-gui#104]
I have download and installed as reported on the guide. 
After `python start.py` I get:
```
authenticate ***** to https://auth.instapy.io/login ...
logged in with user: *****
error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)
closed socket
```

I'm running it in virutalenv with ptyhon3

```
python --version
Python 3.6.9

pip freeze
beautifulsoup4==4.9.1
certifi==2020.4.5.2
cffi==1.14.0
chardet==3.0.4
clarifai==2.6.2
configparser==3.8.1
cryptography==2.9.2
decorator==4.4.2
EasyProcess==0.3
emoji==0.5.4
future==0.18.2
googleapis-common-protos==1.52.0
grpcio==1.29.0
idna==2.9
instapy==0.6.8
jsonschema==2.6.0
MeaningCloud-python==1.2.2
pkg-resources==0.0.0
plyer==1.4.3
protobuf==3.12.2
pycparser==2.20
python-dotenv==0.13.0
python-telegram-bot==12.7
PyVirtualDisplay==1.3.2
PyYAML==5.3.1
regex==2020.6.8
requests==2.23.0
selenium==3.141.0
six==1.15.0
soupsieve==2.0.1
tornado==6.0.4
tqdm==4.46.1
urllib3==1.25.9
webdriverdownloader==1.1.0.3
websocket-client==0.57.0
```

**Comment by breuerfelix** [comment]
are you using macos ?

if yes try this https://stackoverflow.com/questions/52805115/certificate-verify-failed-unable-to-get-local-issuer-certificate

**Comment by LorenzoBottaccioli** [comment]
No I'm using Ubuntu 18.04

**Comment by breuerfelix** [comment]
https://www.sslshopper.com/ssl-checker.html#hostname=auth.instapy.io  
https://www.sslshopper.com/ssl-checker.html#hostname=socket.instapy.io  
https://www.sslshopper.com/ssl-checker.html#hostname=config.instapy.io

well my ssl is working totally fine... maybe you are missing some libs ? openssl and stuff on your machine ? but you are able to connect to socket.instapy.io ... so your ssl should be fine i guess...

you get this error everytime you start ?

**Comment by LorenzoBottaccioli** [comment]
I have installed all missing libs of openssl but still getting this error every type I start `python start.py`

**Comment by breuerfelix** [comment]
https://stackoverflow.com/questions/35569042/ssl-certificate-verify-failed-with-python3  
can you try out these things ?

**Comment by LorenzoBottaccioli** [comment]
Uninstalled and reinstalled all openssl libs and it worked (:
