### ISSUE TITLE
Use Instapy-GUI without signing up on instapy.io

### ISSUE THREAD

**Issue by zecsn** [breuerfelix/instapy-gui#110]
Is there a way to use Instapy-GUI without creating account on instapy.io? I don't mind running a web server to mimic instapy.io on my local machine.

**Comment by breuerfelix** [comment]
yeah of course this is possible :)

https://github.com/breuerfelix/instapy-gui/blob/master/docs/contributing.md

the api endpoints the frontend uses are in src/config.js if you wanna build and ship your own frontend :)
