### ISSUE TITLE
 Failed to check comments' status for verification!         b'Message: TypeError: window.__additionalData[Object.keys(...)[0]] is undefined\n'

### ISSUE THREAD

**Issue by GharaibehR** [breuerfelix/instapy-gui#120]
the bot keep spitting this error and never comment yet the bot keeps working and moves to the next post. can someone help please

**Comment by breuerfelix** [comment]
this is more of an instapy issue and maybe you have luck there finding someone to fix this :))  
https://github.com/timgrossmann/InstaPy

sorry to close this but there is nothing i can fix in this REPO here.
