### ISSUE TITLE
Cannot save/modify edited templates

### ISSUE THREAD

**Issue by sashaafm** [breuerfelix/instapy-gui#123]
Hello again @breuerfelix, I'm running into a problem regarding editing templates which seems to be somewhat similar as this old [issue](https://github.com/breuerfelix/instapy-gui/issues/82). When trying to edit certain templates they are not being saved.

Right now I've got a suspicion which is on a malformed payload or some "weird" character breaking the JSON parsing (on the server-side maybe?). Here are a couple of screenshots from the JS console:
![WhatsApp Image 2020-09-30 at 23 09 54](https://user-images.githubusercontent.com/3422400/94798381-71fb1900-03d9-11eb-9fb4-d59b48ce90db.jpeg)
![WhatsApp Image 2020-09-30 at 18 17 18](https://user-images.githubusercontent.com/3422400/94798393-76273680-03d9-11eb-8332-78a424d93bcd.jpeg)

I'm not sure what other information to give to help debug this. It's happening on Firefox (and I believe also on Chrome, but I'll try to doublecheck). I've gone through the actions and values in the template and I couldn't find any JSON breaking characters.

Any idea on how to solve this or how to debug the problem to work around it?

**Comment by breuerfelix** [comment]
Hey ! seems like this is always the same 'job' or actions that triggers this error. could you tell me which one this is ? I mean which InstaPy function this is in the frontend ? That would help me a lot identifying this problem :)

**Comment by ninthsense** [comment]
For me its the "interact_user_followers"

Uncaught (in promise) SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON datamain.0ffab922a2187c4bdf81.bundle.js:6:121109
    kn https://instapy.io/main.0ffab922a2187c4bdf81.bundle.js:6
    InterpretGeneratorResume self-hosted:1468
    AsyncFunctionThrow self-hosted:678

**Comment by Rzbck** [comment]
yep same here i can't modify my template ^^

**Comment by breuerfelix** [comment]
@Rzbck can you also tell me which specific job this is? which function name ?  
i havent got the time to look into this issue yet, still some university stuff going on but i am gathering information so it will be a faster fix when i tackle this :) it will be during the next week i guess !

**Comment by Rzbck** [comment]
i don't really know if its help , 
but i have this message for each job when i simply click on the icone save ,
i think something is wrong when the new json data append in the list 
i don't have for now the exact original issues

**Comment by sashaafm** [comment]
@breuerfelix do you have any idea when you'll be able to tackle this issue? 

I've investigated a bit further and this doesn't seem related to the JSON payloads being malformed. The error says it's a bad JSON payload but I've checked a few of them and they are valid JSON. Unless, this is the server-side not being able to parse the JSON for some reason.

I'm suspicious once the templates reach a certain size/number of actions/number of parameters in certain actions this error happens. For example, I got a large template with many actions and every single one of them gives this error. On the other hand, I've got a small template with one of the same actions as the large one, and this error doesn't happen.

If there's any other info you need to debug this please do tell!

Thank you for your efforts

**Comment by breuerfelix** [comment]
@sashaafm since i am currently moving i barely open my laptop at all. i finally got some free time in november again :)  
also thanks for this info! this is gold and i guess i will fix the issue way quicker with this info :)

**Comment by sashaafm** [comment]
Hello again @breuerfelix, I realize this is an open-source project and we're not entitled to your efforts. I'd just like to ask if there's any chance of this issue being tackled in the near future? I know some people who are depending on this project and we'd like to continue using it.

Is maintenance and support for this project still expected?

Thank you for your time and efforts Felix!

Stay safe.

**Comment by breuerfelix** [comment]
hey @sashaafm thanks for getting back to me since i really can't find the time right now to tackle this even though you helped a lot with all this information! and i am sure i will tackle this 100% during the next weeks :)

well yeah this is open source and i made it open source in hope that when i have other stuff to do, some other people would go on with this project but sadly i am still the only programmer of this whole project... so chances that someone else is digging into this, fixing it, are pretty low right now. but even though i do not plan on adding new features, i still plan on fixing existing bugs and this IS a huge existing bug i really wanna fix!

also if people reading this who are depending on this project because they need it to make money / more money / more efficient money, let me know because finding time for a project like this is easier if you also get smth from the cake because then i can dump some time from other project where i earn some money.

**Comment by breuerfelix** [comment]
@sashaafm i just debugged a little bit but i am not able to recreate this issue ... do  you still have a template that is not working ? if yes could you provide me with the template name ? and maybe your instapy.io username ? you can also send me these things private via email: fbreuer@pm.me

that way i can copy that template to my dev environment to make some further investigations :)

**Comment by sashaafm** [comment]
@breuerfelix thank you so much for your attention to this matter! I've just sent you an email with the data you requested.

**Comment by breuerfelix** [comment]
it is a bug when copying a template... really damn stupid but that should be fixed now!  
but all existing buggy templates are still buggy. after lunch i will write a script that fixes the current DB state so everything should work fine again :) just to let you know bug is found and fixed!

**Comment by breuerfelix** [comment]
also fixed all existing documents! everything should work as expected now :) thanks for the detailed information! without this, i wouldn't be able to fix it that fast :)

**Comment by sashaafm** [comment]
> also fixed all existing documents! everything should work as expected now :) thanks for the detailed information! without this, i wouldn't be able to fix it that fast :)

Thank you so much for your effort. I'll post some feedback once I've confirmed everything's fine now :)
