### ISSUE TITLE
Follow/Like by tags is not working

### ISSUE THREAD

**Issue by AdmiralGaust** [breuerfelix/instapy-gui#127]
Follow by tags or like by tags functionality is not working as expected. It is showing possible posts as 0 and exiting. 

INFO [2020-11-28 17:51:25] Tag [1/1]
INFO [2020-11-28 17:51:25] --> b'natgeo'
INFO [2020-11-28 17:51:35] desired amount: 59 | top posts [disabled]: 9 | possible posts: 0
INFO [2020-11-28 17:51:42] Tag: b'natgeo'
INFO [2020-11-28 17:51:42] Liked: 0
INFO [2020-11-28 17:51:43] Already Liked: 0
INFO [2020-11-28 17:51:43] Commented: 0
INFO [2020-11-28 17:51:44] Followed: 0
INFO [2020-11-28 17:51:44] Inappropriate: 0
INFO [2020-11-28 17:51:45] Not valid users: 0
INFO [2020-11-28 17:51:47] Sessional Live Report: |> No any statistics to show On session start was FOLLOWING 7 users & had 1 FOLLOWERS [Session lasted 59.45 seconds]
INFO [2020-11-28 17:51:48] Session ended!

**Comment by breuerfelix** [comment]
well this could be due to an error in instapy. i will update all actions in the instapy gui database today and also update all templates. maybe this could help but i think it is due to a false setting in instapy :S
