### ISSUE TITLE
Skipping and not liking posts

### ISSUE THREAD

**Issue by mmreuysal** [breuerfelix/instapy-gui#135]
i cannot like any post. GUI give that error:
"INFO [2021-07-21 12:18:14] Cannot detect post media type. Skip https://www.instagram.com/p/XxXxXXXxxxXXxX/"
Link is not important because not liked anyone
and its opening post but shutting down session

![](https://cdn.discordapp.com/attachments/552110294684401664/867351240266743808/unknown.png)

Then i changed like_util "span" to "div" but not working 

![](https://cdn.discordapp.com/attachments/552110294684401664/867339250654904330/unknown.png)

**Comment by Sirman13** [comment]
You resolve this doing a change of Instapy version, just download from git new version oof instapy and replace, take care because quota doesn't work perfectly.

**Comment by erik3165** [comment]
@Sirman13 I was able to fix the inconsistent quota issue by making the code change in this Pull Request found on the original Repo: https://github.com/timgrossmann/InstaPy/pull/6142/commits/fb5029c7d5b76a465396c689c2214ae820250b1b

However, the "Desired Amount" log message is still inaccurate but it now actually likes the quota specified.

**Comment by mmreuysal** [comment]
I tried both but not worked :/

**Comment by erik3165** [comment]
@mmreuysal Have you tried making the change to like_util.py from here: https://github.com/timgrossmann/InstaPy/pull/6143/commits/2b3ab2d99e5a9f9ec8130a26823851203faa38db

I was having this issue where it was skipping posts containing Videos and Carousels and found that the above solution fixed the issue. I hope it works for you too.

**Comment by mmreuysal** [comment]
i tried before but somehow it worked just now thank you everyone 

> @mmreuysal Have you tried making the change to like_util.py from here: [timgrossmann/InstaPy@2b3ab2d](https://github.com/timgrossmann/InstaPy/commit/2b3ab2d99e5a9f9ec8130a26823851203faa38db)
> 
> I was having this issue where it was skipping posts containing Videos and Carousels and found that the above solution fixed the issue. I hope it works for you too.
