### ISSUE TITLE
Instapy Gui - Wrong Login Data

### ISSUE THREAD

**Issue by Layladp** [breuerfelix/instapy-gui#28]
Constantly getting "wrong login data" error after using multiple different instagram profiles.

On my Instagram app I also get "suspicious login attempt"  where I need to verify it was me who tried to login.

Any advice?

**Comment by breuerfelix** [comment]
does your password contain special characters ? like backslash or quotes ? or some other ones ?  
these need to be escaped just like you would do if you use instapy :)

do you run the bot locally on your system ? this login attempt happens the first time you login with another device. maybe you login the first time with a new proxy ? or with your computer ? usually you have to approve this one time and then it should be done :)
