### ISSUE TITLE
don't start

### ISSUE THREAD

**Issue by danielro7587** [breuerfelix/instapy-gui#29]
Hi, I install on windows and open localhost without any problem.
But when I start it, do'nt happen anything.
please help me

![a](https://user-images.githubusercontent.com/41608682/57581940-25f1c080-74d4-11e9-812e-4629f7d5a7d3.jpg)
![d](https://user-images.githubusercontent.com/41608682/57581941-25f1c080-74d4-11e9-82c9-b85eaeb6db10.jpg)

**Comment by BourgeoisBenjamin** [comment]
Same for me

**Comment by breuerfelix** [comment]
when you start docker-compose and don't open the gui on the web, wait until you don't see any new logs in the console and show me a screenshot please :)

maybe some service isn't able to start correctly

**Comment by misafer** [comment]
same here.
use 'docker-compose up -d' to run in background and then 'docker-compose logs instapy' to show logs
![image](https://user-images.githubusercontent.com/959173/59161572-b504ef00-8af9-11e9-8757-ebc7b0aeb49f.png)
![image](https://user-images.githubusercontent.com/959173/59161578-c0f0b100-8af9-11e9-9251-2329962bea17.png)

**Comment by breuerfelix** [comment]
@misafer hey, that doesn't seem to be wrong... have you tried starting the bot via the gui ?
cause the first time you start the bot, it shuts down with this error buts thats okay :) I will program a little nicer error message in there :D

what happens when you hit start in the gui ? does it work ?

**Comment by jobdekker** [comment]
Same for me, the GUI is running smoothly on Digital Ocean, but i can't start the Bot via the GUI.
When start, the status change to "loading" and nothing happens.

**Comment by Ancinek** [comment]
Same for me :(

**Comment by breuerfelix** [comment]
I solved this issue with version 2 since the start / stop mechanism is completely different because the user doesn't have to use docker at all.

@Ancinek also the user is allowed to have 0 templates then :P I changed it :D
that's why I will close this issue and hope you guys are able to wait 2-3 weeks until I finally release v2 :) I won't put time into fixing this if its fixed anyways soon :) hope you will understand.
