### ISSUE TITLE
Can't run on Raspberry pi 3

### ISSUE THREAD

**Issue by GaWr26** [breuerfelix/instapy-gui#30]
```
pi@raspberrypi:~/InstaPy $ sudo docker-compose up
Creating network "instapy_instapy-net" with driver "bridge"
Creating volume "instapy_instapy-data" with default driver
Creating volume "instapy_instapy-mongo" with default driver
Creating volume "instapy_instapy-grafana" with default driver
Creating volume "instapy_instapy-influxdb" with default driver
Pulling mongo (mongo:latest)...
latest: Pulling from library/mongo
ERROR: no matching manifest for unknown in the manifest list entries
```

Any ideas for this? I did some searching and it seems like the problem is related to arm64 vs aarch64?

**Comment by breuerfelix** [comment]
sadly there is no docker image for Mongodb for the arm64 ... I already googled that.

in the future we could implement a file based database instead Mongodb or host Mongodb in the cloud so everybody can connect to this one. this would be my preferred version.
