### ISSUE TITLE
Docker Compose Error

### ISSUE THREAD

**Issue by veroight** [breuerfelix/instapy-gui#34]
Building webserver
Step 1/4 : FROM nginx:stable-alpine
 ---> ef04b00b089d
Step 2/4 : COPY conf/nginx.conf /etc/nginx/conf.d/default.conf
 ---> Using cache
 ---> a207a84ce123
Step 3/4 : COPY dist /usr/share/nginx/html
ERROR: Service 'webserver' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder889649025/dist: no such file or directory

**Can't execute 'docker-compose up'**

**Comment by breuerfelix** [comment]
this is really strange, may I ask which docker-compose file you used ? 

do you used this one for [unix](https://github.com/breuerfelix/instapy-gui/blob/master/docs/docker-compose.unix.yml) or this one for [windows](https://github.com/breuerfelix/instapy-gui/blob/master/docs/docker-compose.windows.yml) ?

**Comment by Zettt** [comment]
Having the same issue. I'm using the Unix version on macOS 10.14.

**Comment by Zettt** [comment]
Here's a [pastebin](https://pastebin.com/Q8XVbuhU).

**Comment by breuerfelix** [comment]
weird. but you guys are building the images from source :) why do you do that ? you can just use the pre built ones from the dockerhub :)

just don't clone the repo, only download the docker-compose file :)

BUT just contact me on discord and I will invite you to the alpha cloud group. v2 runs without docker at all. its getting tested right now, I hope to release it during this or next week :)

**Comment by Zettt** [comment]
> weird. but you guys are building the images from source :) why do you do that ?

Because that is common procedure. You clone a repository, execute the Docker command, and the app figures itself out. I find your process more complicated because the process is uncommon. Maybe it's easier to avoid such issues by just adding a line that says not to clone the repository to the README? 

I got it working by the way. Good work on the app. Looks fabulous.

**Comment by breuerfelix** [comment]
you are right ... I should change that in the readme :) but I wont do that since its not needed anymore soon :D

yes its the same one :) everything is free but I appreciate your help ! thanks a lot :)
