### ISSUE TITLE
It seems you dont love lowercase so much =(

### ISSUE THREAD

**Issue by fbraz3** [breuerfelix/instapy-gui#37]
> I see camel cases
> How often do you see them?
> All the time!
![image](https://user-images.githubusercontent.com/10731570/59718485-ad77d100-91f0-11e9-92c5-b2a9db0b3b9a.png)

![image](https://user-images.githubusercontent.com/10731570/59718212-0a26bc00-91f0-11e9-891d-838abbfc8d7f.png)

PS: Just kidding, man. Please keep going this awesome project!

**Comment by breuerfelix** [comment]
hahahaha :D thanks mate ! maybe I can go full lowercase with version 2 :P   

I thought uppercase title looks more business like ... maybe I was wrong !
