### ISSUE TITLE
instapy exited with code 1

### ISSUE THREAD

**Issue by Ourlet** [breuerfelix/instapy-gui#38]
Hi guys,
I am facing an issue while running docker-compose.

While running docker-compose up, the last message received:"instapy exited with code 1" with the error message on the browser on http://localhost - ERR_CONNECTION_REFUSED

Thank you,
Xavier

**Comment by MPJHorner** [comment]
run `docker ps -a` get the container ID and run `docker logs $containerId`, paste them here.
Is port 80 available?

**Comment by breuerfelix** [comment]
are you running on windows with the docker toolbox ?

**Comment by Ourlet** [comment]
Hi guys, thank you for your reply.
@MPJHorner, please find below the result of your suggested command
`CONTAINER ID        IMAGE                                  COMMAND                  CREATED             STATUS                       PORTS                   NAMES
a59470523aa5        kitematic/hello-world-nginx:latest     "sh /start.sh"           5 days ago          Exited (255) 4 minutes ago   0.0.0.0:32770->80/tcp   hello-world-nginx
4c53bcabc7f1        felixbreuer/instapy-webserver:latest   "nginx -g 'daemon of…"   5 days ago          Exited (0) 5 days ago                                instapy-webserver
3c6665e16aa1        felixbreuer/instapy-socket:latest      "docker-entrypoint.s…"   5 days ago          Exited (0) 5 days ago                                instapy-socket
8ea81090deec        felixbreuer/instapy-grafana:latest     "/run.sh"                5 days ago          Exited (0) 5 days ago                                instapy-grafana
dd8542de9415        felixbreuer/instapy-config:latest      "python3 -u start.py"    5 days ago          Exited (137) 5 days ago                              instapy-config
472aafff6989        felixbreuer/instapy:latest             "sh start.sh"            5 days ago          Exited (0) 5 days ago                                instapy
da2b3fab87e1        mongo:latest                           "docker-entrypoint.s…"   5 days ago          Exited (137) 5 days ago                              instapy-mongo
617f27b645a8        influxdb:alpine                        "/entrypoint.sh infl…"   5 days ago          Exited (137) 5 days ago                              instapy-influxdb`

`$ docker logs $containerId
"docker logs" requires exactly 1 argument.
See 'docker logs --help'.

Usage:  docker logs [OPTIONS] CONTAINER [flags]

Fetch the logs of a container`

@breuerfelix, actually I am running on windows. I am happy to wait for release v2.

Thanks again

**Comment by breuerfelix** [comment]
@Ourlet you can have a look at the branch 'auth-service' and go through the readme there to already alpha test version 2 :)

let me know if the error still persist there !
