### ISSUE TITLE
Instapy exited with code 0

### ISSUE THREAD

**Issue by zethis** [breuerfelix/instapy-gui#39]
Hi guys,
I am not able to run instapy right now,
one of container (named instapy) exit with code 0 and i can't like or follow ...
Here is the docker logs of the container:
docker logs -f instapy
added actions to mongodb

**Comment by zethis** [comment]
I think, the problem is login side ...
I don't see anything in the Dashboard tab

**Comment by breuerfelix** [comment]
hey,

I will also backlog this issue since we are releasing v2 really soon, I hope during next week.

you can also alpha test it right now, just visit the branch 'auth-service' and go through the readme there :)

if this issue still persists there, I will have a look at it !

**Comment by zethis** [comment]
Ok perfect, i close it !
