### ISSUE TITLE
headless browser support 

### ISSUE THREAD

**Issue by srozov** [breuerfelix/instapy-gui#49]
So first of all, thanks for this awesome project! :) 
As you might have noticed lately, ig seems to block headless browsers after a while... So I tried to set `headless_browser = False` in `start.py` but get this error :

`Message: unknown error: Chrome failed to start: exited abnormally (unknown error: DevToolsActivePort file doesn't exist) (The process started from chrome location /usr/lib/chromium/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.) (Driver info: chromedriver=73.0.3683.103,platform=Linux 4.9.125-linuxkit x86_64) Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/instapy/browser.py", line 147, in set_selenium_local_session chrome_options=chrome_options) File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__ desired_capabilities=desired_capabilities) File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__ self.start_session(capabilities, browser_profile) File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session response = self.execute(Command.NEW_SESSION, parameters) File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute self.error_handler.check_response(response) File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response raise exception_class(message, screen, stacktrace) selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally (unknown error: DevToolsActivePort file doesn't exist) (The process started from chrome location /usr/lib/chromium/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.) (Driver info: chromedriver=73.0.3683.103,platform=Linux 4.9.125-linuxkit x86_64)`

I noticed you're not using the instapy-chromedriver, could that be the reason?

**Comment by breuerfelix** [comment]
you cant run a non-headless version in a headless environment :) so this is not able in docker ! 

But in V2 (currently I prepare the release, hope to be tomorrow) this is possible again because you don't need docker at all :)

just be patient for a while !

But remember, if you wanna run non-headless, you need to run the client on a non-headless environment. So a server or a raspberry pi wont be able to do that :)
