### ISSUE TITLE
Error with set_quota_supervisor

### ISSUE THREAD

**Issue by GaWr26** [breuerfelix/instapy-gui#54]
Something is wrong in set_quota_supervisor
```
Traceback (most recent call last):
  File "bot.py", line 136, in <module>
    getattr(session, job['functionName'])(**arguments)
  File "/home/pi/InstaPyGUI/env/lib/python3.7/site-packages/instapy/instapy.py", line 4798, in set_quota_supervisor
    peaks = {"likes": {"hourly": peak_likes[0],
NameError: name 'peak_likes' is not defined

```

**Comment by breuerfelix** [comment]
yep there was an issue ! thanks for reporting :) I fixed it.

Could you please reinstall the requirements ? just run the command again and it will update automatically :)

let me know if this worked !

**Comment by GaWr26** [comment]
Yes, it works now. Thank you very much!

i had to upgrade tough: `pip3 install -r requirements.txt --upgrade`

**Comment by breuerfelix** [comment]
thanks for this info ! I added it to the update.sh file :)
