### ISSUE TITLE
Scheduling, multiple accounts & setup

### ISSUE THREAD

**Issue by GaWr26** [breuerfelix/instapy-gui#55]
Hey Felix,

is there a way to schedule the execution of scripts? How would I automate it for daily execution? I don't want to click run every day :)

Also how would I handle multiple instances? Do I need a virtual environment and login on instapy.io for each instance?

How about a way of exporting and importing templates? It's pretty tedious setting everything up if you use multiple parameters. Also the tags, comments etc. field won't let me paste multiple entries at once. Is there a trick?

Thanks again for the great work put into this!

**Comment by breuerfelix** [comment]
Hey,

Scheduling scripts is the next big step on the roadmap :) we thought about implementing this as a 'paid' feature so everybody who is on the 5+ tier on open collective is able to use this. This will help us alot in further programming. But yet, its not started. (but I programmed everything so this wont be too hard to implement)

if you want to run multiple instances do it like that:
* copy the whole folder to another place
* edit `.env` file and change the `IDENT=` to something else
* start the new client

in the select box of the start panel you know can choose between 2 bots and you can start them in parallel :) (I will add that to the docs :D)

exporting and importing is not possible but next step will be to copy and existing template.
so once you did one, you don't have to type everything again if these are similar.

thanks for your feedback ! I will add some more documentation today :) I love your ideas, keep posting them so the development strives in the right direction :)
