### ISSUE TITLE
Question about comments

### ISSUE THREAD

**Issue by GaWr26** [breuerfelix/instapy-gui#59]
Is this the right format to enter for comments with Emojis: 
`u'What an amazing shot! :heart_eyes: What do you think of my recent shot?`

not sure how to test this without making a fool out of myself :)

**Comment by GaWr26** [comment]
found out it needs to be without the leading u
`What an amazing shot! :heart_eyes: What do you think of my recent shot?`

**Comment by breuerfelix** [comment]
thanks for posting this info ! I will put this into the description of this function (when you press show info)
