### ISSUE TITLE
No module named dotenv

### ISSUE THREAD

**Issue by thomasthomas11235** [breuerfelix/instapy-gui#62]
Hi,
As the title says, I'm getting error no module dotenv. 
I've tried python3 -m pip install python-dotenv, and even though it installed ok, I still get the error when I run startClient.sh?

Thanks

**Comment by breuerfelix** [comment]
may I ask which operating system do you have and which version ?

could you cd into the folder and run `./env/Scripts/python3.exe -m pip install python-dotenv` .

Looking forward to these infos :)
