### ISSUE TITLE
Reloading instapy.io leads to a 404

### ISSUE THREAD

**Issue by Zettt** [breuerfelix/instapy-gui#70]
Doesn't work on my Chromium browser. ⌘R on any page, and it gives me the 404 page.

Otherwise good work, Felix.

**Comment by breuerfelix** [comment]
thanks alot !

yeah I need to get away from GitHub Pages as a Webserver ...

once I finished reducing the blocks on instapy I will get back to developing :P

**Comment by breuerfelix** [comment]
I got it working even with GitHub pages :)

thanks for the issue !
