### ISSUE TITLE
Session ended!

### ISSUE THREAD

**Issue by tellmoitas** [breuerfelix/instapy-gui#71]
INFO [2019-07-25 20:46:29] Sessional Live Report: |> No any statistics to show On session start was FOLLOWING 424 users & had 71 FOLLOWERS [Session lasted 1.25 minutes]
INFO [2019-07-25 20:46:31] Session ended!

**Comment by breuerfelix** [comment]
all actions in the templates were disabled -> solved the problem !

**Comment by giacomoalonzi** [comment]
I have the same issue but if I try to enable it I have error 500 in console
