### ISSUE TITLE
error KeyError: 'media'

### ISSUE THREAD

**Issue by lucasaraujoo** [breuerfelix/instapy-gui#78]
..........................................................................
INFO [2019-08-26 15:59:16] [jamilecastilhomakeup]  Logged in successfully!
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2019-08-26 15:59:17] [jamilecastilhomakeup]  Saving account progress...
INFO [2019-08-26 15:59:24] [jamilecastilhomakeup]  Tag [1/1]
INFO [2019-08-26 15:59:25] [jamilecastilhomakeup]  --> b'maquiagem'
INFO [2019-08-26 15:59:43] [jamilecastilhomakeup]  desired amount: 45  |  top posts [disabled]: 9  |  possible posts: 14167547
INFO [2019-08-26 16:00:04] [jamilecastilhomakeup]  Like# [1/45]
INFO [2019-08-26 16:00:05] [jamilecastilhomakeup]  https://www.instagram.com/p/B1m5zDpJW_H/

INFO [2019-08-26 16:00:12] [jamilecastilhomakeup]  Sessional Live Report:
        |> No any statistics to show

On session start was FOLLOWING 474 users & had 438 FOLLOWERS
[Session lasted 1.84 minutes]

OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2019-08-26 16:00:13] [jamilecastilhomakeup]  Session ended!
ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

Traceback (most recent call last):
  File "bot.py", line 143, in <module>
    getattr(session, job['functionName'])(**arguments)
  File "C:\Users\Lucas\Desktop\instapygui\env\lib\site-packages\instapy\instapy.py", line 1908, in like_by_tags
    self.logger)
  File "C:\Users\Lucas\Desktop\instapygui\env\lib\site-packages\instapy\like_util.py", line 590, in check_link
    media = post_page[0]['media']
KeyError: 'media'

**Comment by naldoxable** [comment]
Check the template settings and post a screenshot of the like by tag

**Comment by naldoxable** [comment]
Is the media field empty? Even blank space should be removed. Post a screen of the whole template

**Comment by naldoxable** [comment]
Are you using the same folder and files for the other account or are you launching the bot from another folder?

**Comment by naldoxable** [comment]
Probably there are some files corrupted. Start the update and try again reconfiguring the account.

**Comment by naldoxable** [comment]
Try to change only the account, using the same template and same files

**Comment by breuerfelix** [comment]
I just updated to Instapy 0.6.x.

please do the following to be sure to have the lastest version:

- do a clean setup again on your computer
- on instapy.io click the save button on settings and template you wanna use. (this will reconfigure the settings / templates for the new instapy version)
- try to start again 

note: the new version uses firefox only so make sure you have firefox installed :)
