### ISSUE TITLE
Raspberry setup stuck on "Failed building wheel for instapy"

### ISSUE THREAD

**Issue by giacomoalonzi** [breuerfelix/instapy-gui#79]
Hello everybody
I'm trying to install it on raspberry but I'm stuck on setup script:

```
Building wheels for collected packages: instapy
  Running setup.py bdist_wheel for instapy ... error
  Complete output from command /home/pi/dev/instapy/env/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-529ydjpt-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpven86igwpip-wheel- --python-tag cp35:
  /usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
    warnings.warn(msg)
  /usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'project_urls'
    warnings.warn(msg)
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for instapy
  Running setup.py clean for instapy
Failed to build instapy
```
After that seems to run with no problem but when I run `bash startClient.sh`
I have this error:
```
  File "start.py", line 65
    print(f'authenticate {username} to {url} ...')
                                                ^
SyntaxError: invalid syntax
```

is related? any hint?

**Comment by giacomoalonzi** [comment]
for the first part I solved with
`sudo python3 -m pip install -r requirements.txt --upgrade`
no luck for the second part :\

**Comment by breuerfelix** [comment]
@giacomoalonzi the second problem is because you use python2 instead of python3 :)

**Comment by giacomoalonzi** [comment]
Hey @breuerfelix in the startClient.sh is specified to use python3 
```
#!/bin/bash          
./env/bin/python3 start.py
```
what you think about?

**Comment by breuerfelix** [comment]
what the output from `python3 --version` ?

**Comment by giacomoalonzi** [comment]
> python3 --version

Python 3.5.3

**Comment by breuerfelix** [comment]
ahh okay this string format requires python3.6. are you somehow able to install this python version ?

**Comment by giacomoalonzi** [comment]
yep, I could try! I'll update you asap thanks!

**Comment by giacomoalonzi** [comment]
@breuerfelix I update to 3.6 on raspberry but in the script you are going to use the version inside .env folder. And that version is 3.5.
I also tried to run `python3 start.py` but this time I have

```
Traceback (most recent call last):
  File "start.py", line 1, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
```

**Comment by giacomoalonzi** [comment]
All problems are solved by installing the last update S.O on raspberry. :)

**Comment by giacomoalonzi** [comment]
All problems are solved by installing the last update S.O on raspberry. :)
