### ISSUE TITLE
unexpected keyword argument

### ISSUE THREAD

**Issue by devtobi** [breuerfelix/instapy-gui#80]
Thanks for your work and upgrade to 0.6
I got a new error when trying to start the bot via the gui.
`__init__() got an unexpected keyword argument 'browser_binary_path'`

Firefox is installed.

Thanks in advance :)

**Comment by breuerfelix** [comment]
damn ... I forgot removed this line :D thank you, fix is on the way !

**Comment by breuerfelix** [comment]
should be fixed now ! try my update please :)

**Comment by devtobi** [comment]
works like a charm now :) Thanks

**Comment by breuerfelix** [comment]
thanks for the quick feedback with this bug ! people like you make this community awesome :))
