### ISSUE TITLE
template editing issue

### ISSUE THREAD

**Issue by devtobi** [breuerfelix/instapy-gui#82]
Back with another bug?
When trying to edit settings via the gui (e.g quota supervisor) hitting the save button doesn't do anything in my case.
The old settings always get restored.

**Comment by giacomoalonzi** [comment]
Can you check the browser console if you get ERROR 500?
![Screenshot 2019-08-29 at 15 06 05](https://user-images.githubusercontent.com/16420302/63942731-96662280-ca6e-11e9-918a-9f257e25edab.png)

**Comment by devtobi** [comment]
Yes I get a error 500 but it says:
`Unhandled Promise Rejection: SyntaxError: The string did not match the expected pattern.`

**Comment by giacomoalonzi** [comment]
@devtobi yes probably is a validation error. I also checked the payload via network but seems no issues. We must wait for @breuerfelix for more details :)

**Comment by breuerfelix** [comment]
I will try to solve this issue tomorrow :) could you give me some more details ?

it only happens when you press save ? and only for which actions ?

**Comment by giacomoalonzi** [comment]
@breuerfelix I incurred in this issue twice. The first time I solved with a new template and I had no issue till yesterday. 
Yesterday I incurred again in this issue and it's happening when you try to enable/disable issue or press save. As I said seems like a validation error on the server-side. 
I tried to disable an action and this is the payload
```json
{"action":"update","job":{"functionName":"set_mandatory_language","namespace":"mynamespace-2","active":false,"params":[{"name":"enabled","value":true}],"_id":{"$oid":"5d66bdf507f6a8733a728e27"}}}```
at this url `https://config.instapy.io/namespaces/mynamespace-2/jobs/5d66bdf507f6a8733a728e27`
get error 500.

I could help you to debug the code but I must configure locally first, dunno if I can do it today 🔥
Anyway, thank you for your time :)

**Comment by giacomoalonzi** [comment]
@breuerfelix Maybe I found the issue. 
This happens when you modify the namespace in the frontend but it for some reason don't be updated at backend side. 
I noticed a different namespace in the response and I tried to modify namespace as the response is, and it works again.

Hope this will help!

**Comment by breuerfelix** [comment]
@giacomoalonzi what do you mean with different namespace ?
usually the frontend should always updates depending on the backend (backend got higher prio) so I don't know when this could happen.

could you give me a really short step by step on how to reproduce this issue ? :) this would be amazing.

**Comment by giacomoalonzi** [comment]
> @giacomoalonzi what do you mean with different namespace?
> usually the frontend should always update depending on the backend (backend got higher prio) so I don't know when this could happen.
> 
> could you give me a really short step by step on how to reproduce this issue? :) this would be amazing.

Yes of course.
I incurred in this issue when I modified the name of a template (eg. mytemplate in mytemplate-2)
this for me cause the issue in fact when I renamed the template as original name (mytemplate) the server has responded with no issue.
