### ISSUE TITLE
gui-features link no more working

### ISSUE THREAD

**Issue by DrRek** [breuerfelix/instapy-gui#90]
Hey man,
in other to run `/services/actions` there are python requirements to install. One of them it's https://github.com/timgrossmann/InstaPy/zipball/gui-features, however it's not working anymore.

Is there an alternative to initialize the db? Can i find the content of this url somewhere else?

**Comment by DrRek** [comment]
Found a solution. Removed that line from the rquirements. Added `instapy` to requirements
executed `docker run -it --rm --name my-running-script -v "$PWD":/usr/src/myapp -w /usr/src/myapp python:3 bash` from the actions folder, added it to the network with `docker network connect instapy-gui_default my-running-script` in another terminal.
Edited the database.py line 4 to `mongodb://<user>:<password>@mongo:27017`
In the first terminal executed `pip install -r requirements.txt && python main.py`

Of course all the procedure could be optimized (you don't have to run the script in a separate container, i did because on my main system python-dotenv doesn't work). Of course however if you don't want to use it the line 4 in database.py should be `mongodb://<user>:<password>@localhost:27017`

**Comment by breuerfelix** [comment]
ouh yeah i forgot to change that requirement when i merged the gui features branch into the main branch on instapy :)

thanks for mentioning this !

since i was the only one who updated the database, no one cared about that :D i will fix that :)

**Comment by breuerfelix** [comment]
btw yo set up everything for self hosting right ? would you mind documenting this really short in a markdown file in the docs folder and make a pull request ?

could be quick and dirty and i will polish that a little bit :)

only if you got time !

**Comment by DrRek** [comment]
Actually i think that the documentation step for self hosting should be as minimal as run `docker-compose up`.
However it looks like this does not work, there are a few problems which i think should be directly solved into the sources which i would try to list here.

*Note: in my case i'm interested into running each service into a container (also the front-end) for future deployment on some cloud provider*

- Front-end should be added as a separate container into the services folder
- Each service should have a readme file with a few lines explaining what it's meant for and all the enviroment variables needed.
- All the services should have a consistent way to declare all the required environment variables (for example you could add and .env file with all the required variables, commit it and then add it to gitignore, or maybe a better approach would be to have all the env var written inside the readme or an .env.example)
- Requirements should be checked, as an example many have dotenv dependency which you probably have already installed on your main system. However i didn't and this caused different container to crash.
- Maybe the more important thing is that each container to comunicate with the other should have the correct address (for example if config want to communicate with mongo the correct address is "mongo:27017" and not "locahost:27017")
- Database names, secrets and things like that (aka variables common to many container) should be defined only in one place (maybe in the docker compose file env variables declaration part? i don't know if there is some a better location)
- There was a container (i don't remember which) who was always failing beacause he was trying to connect to an instapy account which was not created (because i wasn't yet registered). Maybe to solve this a default account could be created on db inizialization. (I think this is low priority and you could add to the documentation to connect to localhost:8080 and register with the same credentials given to the container)

After doing this in order to run all the system you should only run `docker-compose up` and everything should work by default.

After reading all this you might think that I'm just a snooty pain in the ass that only wants to criticize. Well, i don't XD
I only mentioned the problems i've found in these days and I tried to give you some suggestion which if you want we could further discuss, I really appreciate the work you've done (I'm really sure that if I had to do something like I wouldn't come up with such a clean code/organization!).
Thank you!

p.s. I hope i made myself clear, but i'm not mother-tongue and i'm too lazy to re-check it. If you want more information or even just some clarification just let me know

**Comment by breuerfelix** [comment]
first of all, thanks for your time to take the review !!

well i think that everything should already be in such a state except 3 things.

the instapy container:  
this one is just in the main docker compose file because travis needs to build it and push it to dockerhub, if you self host all of that, you should use the docker-compose.host.yml. the instapy container shouldnt be in there :)  
also this one will read in all environement vars from .env so you can set your own mongo URL through this :)

the actions service:

this service is for manual use only so there is no docker container for this :) this service also reads in the environment file so you can set your own mongo url through this :)

the frontend:

this will be hosted on github pages since i thought i could reduce traffic on my DO droplet since i dont wanna pay that much ( i dont earn money with this) and github pages is fast as hell anyways :D

if you just want to do docker compose up you need the following:

- use docker-compose.host.yml
- add a mongodb service to this (i use mongodb atlas free tier which got 512 mb and is waaaay enough, i got 2.4MB with 1,5k users :D)
- add a service for the frontend for this
- create .env file with all env vars
- docker compose up
- inject actions
- if you want ssl you can also spin up docker compose.ssl.yml which automatically does this :)

i hope this helped you a little bit and yeah ... it would be awesome to just do docker-compose up. when instapy v2 is more stable i can try to adjust that :)

i really love this project and would like to go on programming but ... we first need to get instapy non blocking :D

i

**Comment by DrRek** [comment]
To be onest i'm just a beginner in the DevOps world so sorry if I said some nonsense (for example I didn't even know about github pages till today and know it makes sense to avoid creating it as another service).
However I understood that this is most probably the field I want to work in once graduated. At the moment I plan on using this as side project, while studying and working.
My proposed goal is to transform this project into something usable for everyone (and maybe even sell the service to few local business here in italy to make a few bucks, why not).

Of course to reach this goal there are many difficult steps (at least for me :laughing:), you have already mentioned the first one
> we first need to get instapy non blocking

I would like to use instapy as another shared service instead of having each user set up their own and allow them to only set up a proxy (in some far away iteration I would even like to simplify this part also)
Do you think it's possible? What would be the main difficulties in your opinion?
Honestly i was first trying to make your repo build and work locally (I think i'm almost there, i have just a little issue about settings not saving the username and password, but I think i'll figure it out by today) and then I'll start working on this. From instapy doc it's possible to run in headless mode and to work with [threads](https://github.com/timgrossmann/InstaPy/blob/master/DOCUMENTATION.md#running-in-threads) but i didn't dive to much in it yet.

Btw I just had time to look at docker-compose.ssl.yml which i didn't noticed before and it looks cool, I'm sure I'll have fun understanding how it works :fire:

**Comment by breuerfelix** [comment]
i love the way that you are engaged of getting this up and running / improving it !

i could just offer you some skype / discord conversation so we can talk about this and i can explain a little more the architecture and pitfalls ? and i can answer your detailed questions way easier :D

i think this would save you alot of time you can focus on other stuff :) i know i bet you already learned alot during this setup but you gonna learn way more than that if you can continue and not having to face issues cause of the lack of my documentation :D
