### ISSUE TITLE
`start` function in /services/sockets does not get called

### ISSUE THREAD

**Issue by DrRek** [breuerfelix/instapy-gui#92]
I've been debuging on this for days. I managed to setup anything, however there is still on problem left I'm not able to solve.

Once clicked onto the start button in the `/start` page (after selecting all the proper information) the front-end sends two messages to the instapy container, one with the start request and the other with the status request.

Both requests reaches the `on_message()` func in `/service/instapy/main.py` but only the status one gets forwarded to the proper handling function. The start request reaches the line 40 `HANDLERS[data['handler']](ws, data)` but the function `start` is not being called.

After debuging it looks like both `data['handler']` and `HANDLERS[data['handler']]` have correct values. The execution just terminates at that line without calling the start function and without even continue the execution (line 41 etc.)

Have you ever experienced this issue?

**Comment by DrRek** [comment]
My bad, i've just discovered this is not the real error, i will open a new issue if i can't manage to solve it

**Comment by breuerfelix** [comment]
this is really strange ! so your problem is, that it wont start right ?

you can describe what is happenining / not happening so maybe i can help you solve this issue since i know any pitfall of my application :D

**Comment by DrRek** [comment]
Yeah that was just an issue created by me while debugging. The real problem is that when I press start on the start page i get the error

`instapy_1  |  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
instapy_1  | Custom workspace set: "/usr/instapy/assets/InstaPy" :]
instapy_1  | InstaPy Version: 0.6.5
instapy_1  |  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
instapy_1  | Workspace in use: "/usr/instapy/assets/InstaPy"
instapy_1  | WARNING [2019-10-29 16:13:14] [None]  Heeh! Error occurred while getting a DB profile for 'None':
instapy_1  | 	b'NOT NULL constraint failed: profiles.name'
instapy_1  | Traceback (most recent call last):
instapy_1  |   File "bot.py", line 125, in <module>
instapy_1  |     session = InstaPy(**instapy_args)
instapy_1  |   File "/usr/local/lib/python3.7/site-packages/instapy/instapy.py", line 306, in __init__
instapy_1  |     get_database(make=True)  # IMPORTANT: think twice before relocating
instapy_1  |   File "/usr/local/lib/python3.7/site-packages/instapy/database_engine.py", line 66, in get_database
instapy_1  |     get_profile(name, address, logger) if profile_id is None or make else profile_id
instapy_1  |   File "/usr/local/lib/python3.7/site-packages/instapy/database_engine.py", line 167, in get_profile
instapy_1  |     profile = dict(profile)
instapy_1  | TypeError: 'NoneType' object is not iterable`

Inspecting settigs entry into the database using mongodbcompass i've noticed that settings are being saved without username and password (null values are being placed instead).

Maybe I have some problem with `coding_wrapper()`

btw is there a way to `print` to console even during async calls? this would help me a lot during debug.

**Comment by DrRek** [comment]
Fixed, to prevent other people from struggling with this problem simply replace `CIPHER_SECRET` default value which atm it's `instapysecret` with a valid Fernet key. You can generate one using `key=frt.generate_key()` and change the default value `settings.py`
p.s. I don't know if this key is used anywhere else in the application, if it is please let me know :D

**Comment by DrRek** [comment]
ops, my bad :smile: 
i didn't read that file
