### ISSUE TITLE
Cannot Start Connection to Instapy.io - RPI2

### ISSUE THREAD

**Issue by fpibbs** [breuerfelix/instapy-gui#93]
I'm on RPI2, raspbian, old instapy installation on python3 disabled at the moment:

pi@raspberrypi:~ $ bash startClient.sh
  File "start.py", line 64
    print(f'authenticate {username} to {url} ...')
                                                ^
SyntaxError: invalid syntax
pi@raspberrypi:~ $

what about this error?

**Comment by breuerfelix** [comment]
hey,

you need python 3.6 for this client in order to run.

so if you get this on the pi installed it will work :)

**Comment by fpibbs** [comment]
Hi Felix, hi installed python 3.6...

https://medium.com/@isma3il/install-python-3-6-or-3-7-and-pip-on-raspberry-pi-85e657aadb1e

still receive the error.

**Comment by breuerfelix** [comment]
okay so go into startClient.sh and change `python` to `python3`
