### ISSUE TITLE
Any option to not Skip Private users ? 

### ISSUE THREAD

**Issue by BenlamrabetBahaeEddine** [breuerfelix/instapy-gui#96]
Hello, 
i have made everything works, but it seems like the process is always skipping private users :

Not a valid user: ####  is private account, by default skip

is there any solution how to change it ?

Regards

**Comment by breuerfelix** [comment]
hey,

yeah you can look it up in the official instapy documentation :)

https://github.com/timgrossmann/InstaPy/blob/master/DOCUMENTATION.md

it is the action called `set_skip_private` :)
