### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by Curioo** [breuerfelix/instapy-gui#97]
Hey, i repeatedly get this error when running `bash startClient.sh ` : error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)
closed socket

Is there a way to fix this? thanks!

**Comment by Curioo** [comment]
I fixed it :)

**Comment by breuerfelix** [comment]
perfect, there should be also a part about that in the troubleshooting section on the readme :)
