### ISSUE TITLE
start.py

### ISSUE THREAD

**Issue by ShSood** [breuerfelix/instapy-gui#98]
What should I do?

Traceback (most recent call last):
  File "start.py", line 175, in <module>
    TOKEN = get_token(username, password)
  File "start.py", line 64, in get_token
    print(f,"authenticate {username} to {url} ...")
NameError: global name 'f' is not defined

**Comment by breuerfelix** [comment]
use a python version which is >= 3.6

i will update that in the faq maybe cause this seems to be a common issue
