### ISSUE TITLE
Problem with Selenium

### ISSUE THREAD

**Issue by devtobi** [breuerfelix/instapy-gui#99]
I just setup the tool on a Raspberry Pi 3.
After clicking Start on instapy.io I only get the following error on my Pi.
![image](https://user-images.githubusercontent.com/28538704/79158089-ff1fc680-7dd5-11ea-882c-5d7067325399.png)

Do you have any clue what could cause this issue? Installed firefox-esr on the Pi as well.

Thanks in advance :)

**Comment by breuerfelix** [comment]
the path on the last line looks a little weird, can you confirm that the geckodriver is located there ? and also that it got all permissions to execute ?

**Comment by devtobi** [comment]
Yes gecko driver is located there. I gave it all permissions but still does not work. I see that inside assets/gecko/v.0.26.0 geckodriver for linux32 is in there. Do I have to use a different version for RaspberryPi? And do I have to add gecko driver to the PATH variable manually?

**Comment by breuerfelix** [comment]
you manually need to edit this line: https://github.com/breuerfelix/instapy-gui/blob/d3d11eba16239a8a48600696e5d29654ccf5b634/services/instapy/bot.py#L119  
and add a new line with the following content:

```python
instapy_args['geckodriver_path'] = "path to your geckodriver executable"
```

and then you can do the following: try to find the correct version of your firefox-esr and download the exact geckodriver version. (or try to install the exact geckodriver package) and provide the link to your geckodriver executable :)

**Comment by devtobi** [comment]
I did not manage to get it to work yet. But I tried using the provided docker image and after starting the container all it get in the log of the container is `standard_init_linux.go:211: exec user process caused "exec format error"` a couple of times. Im using the newest docker release on my Raspberry Pi 3

**Comment by breuerfelix** [comment]
@devtobi yeah sadly thats the error here...

the problem with ARM images is, dockerhub cannot build them in their pipeline. so i  have to tell travis to build and publish them. which is okay :)

the other problem is that i dont have a RPI so i cant even test these images :)

looking forward for any PR with a arm.Dockerfile for the instapy service (since all the others dont need that :))
